const HANWHA_PLAYERS = [
  { num: '19', name: '왕옌청', pos: '투수' },
  { num: '27', name: '이민우', pos: '투수' },
  { num: '38', name: '김종수', pos: '투수' },
  { num: '48', name: '원종혁', pos: '투수' },
  { num: '49', name: '윤산흠', pos: '투수' },
  { num: '57', name: '조동욱', pos: '투수' },
  { num: '58', name: '박상원', pos: '투수' },
  { num: '60', name: '쿠싱', pos: '투수' },
  { num: '61', name: '정우주', pos: '투수' },
  { num: '64', name: '권민규', pos: '투수' },
  { num: '66', name: '주현상', pos: '투수' },
  { num: '69', name: '강건우', pos: '투수' },
  { num: '96', name: '박준영', pos: '투수' },
  { num: '99', name: '류현진', pos: '투수' },
  { num: '13', name: '최재훈', pos: '포수' },
  { num: '59', name: '허인서', pos: '포수' },
  { num: '5', name: '이도윤', pos: '내야수' },
  { num: '7', name: '심우준', pos: '내야수' },
  { num: '8', name: '노시환', pos: '내야수' },
  { num: '16', name: '하주석', pos: '내야수' },
  { num: '22', name: '채은성', pos: '내야수' },
  { num: '50', name: '강백호', pos: '내야수' },
  { num: '95', name: '황영묵', pos: '내야수' },
  { num: '10', name: '이진영', pos: '외야수' },
  { num: '25', name: '김태연', pos: '외야수' },
  { num: '30', name: '페라자', pos: '외야수' },
  { num: '37', name: '이원석', pos: '외야수' },
  { num: '51', name: '문현빈', pos: '외야수' },
  { num: '54', name: '오재원', pos: '외야수' },
];

module.exports = { HANWHA_PLAYERS };